version: '3.8'

services:
  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CART_URL=http://localhost:3001
    volumes:
      - ./home:/app
      - /app/node_modules
      - /app/.next
    networks:
      - micro-frontend

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HOME_URL=http://localhost:3000
    volumes:
      - ./cart:/app
      - /app/node_modules
      - /app/.next
    networks:
      - micro-frontend

networks:
  micro-frontend:
    driver: bridge